# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
on_event = 'InsertEnter'
hook_add = '''
let g:deoplete#enable_at_startup = 1

" <TAB>: completion.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"

" <CR>: close popup and save indent.
inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"
'''

# [[plugins]]
# repo = 'zchee/deoplete-clang'
# hook_source = '''
# let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/3.9.1/lib/libclang.dylib'
# let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/3.9.1/lib/clang/'
# '''
# on_ft = ['c', 'cpp', 'cmake']
# depends = ['deoplete.nvim']

# [[plugins]]
# repo = 'Valloric/YouCompleteMe'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
on_event = 'InsertEnter'
depends = 'deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_event = 'InsertEnter'
on_ft = 'python'
hook_add = '''
let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
if = 'has("python3")'
on_cmd = 'Denite'
hook_add = '''
nnoremap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
nnoremap <silent> <C-p> :<C-u>Denite file_rec<CR>
nnoremap <silent> sp :<C-u>Denite file_rec<CR>
nnoremap <silent> sc :<C-u>DeniteBufferDir file_rec<CR>
nnoremap <silent> <C-b> :<C-u>Denite buffer<CR>
nnoremap <silent> sB :<C-u>Denite buffer<CR>
nnoremap <silent> sb :<C-u>Denite buffer/project<CR>
nnoremap <silent> sC :<C-u>DeniteBuffer buffer/project<CR>
nnoremap <silent> <C-u><C-j> :<C-u>Denite line<CR>
nnoremap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
nnoremap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>
nnoremap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
nnoremap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
nnoremap <silent> <C-u><C-r> :<C-u>Denite -resume<CR>
" nnoremap <silent> <C-u>; :<C-u>Denite -resume -immediately -select=+1<CR>
" nnoremap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
" nnoremap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
" nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
 nnoremap <silent> s/ :<C-u>Denite -buffer-name=search -auto-highlight
        \ line<CR>
 nnoremap <silent> s* :<C-u>DeniteCursorWord -buffer-name=search
        \ -auto-highlight -mode=normal line<CR>
 nnoremap <silent> ;g :<C-u>Denite -buffer-name=search
        \ -no-empty -mode=normal grep<CR>
 nnoremap <silent> sn :<C-u>Denite -buffer-name=search
        \ -resume -mode=normal -refresh<CR>
 nnoremap <silent> ;;
        \ :<C-u>Denite command command_history<CR>
 " nnoremap <silent> <C-k> :<C-u>Denite -mode=normal change jump<CR>
'''
hook_post_source = '''
 call denite#custom#var('file_rec', 'command',
 \ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
 call denite#custom#var('grep', 'command',
 \ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
 call denite#custom#var('grep', 'default_opts', [])
 call denite#custom#var('grep', 'recursive_opts', [])
 call denite#custom#alias('source', 'file_rec/git', 'file_rec')
 call denite#custom#var('file_rec/git', 'command',
     \ ['git', 'ls-files', '-co', '--exclude-standard'])
 call denite#custom#source(
     \ 'file_mru', 'matchers', ['matcher_fuzzy', 'matcher_project_files'])
 call denite#custom#source('file_old', 'matchers',
      \ ['matcher_fuzzy', 'matcher_project_files'])
 call denite#custom#alias('source', 'buffer/project', 'buffer')
 call denite#custom#source('buffer/project', 'matchers',
      \ ['matcher_fuzzy', 'matcher_project_files'])
'''

[[plugins]]
repo = 'critiqjo/lldb.nvim'
on_ft = ['c', 'cpp']
hook_add = '''
    nmap <M-b> <Plug>LLBreakSwitch
    vmap <F2> <Plug>LLStdInSelected
    nnoremap <F4> :LLstdin<CR>
    nnoremap <F5> :LLmode debug<CR>
    nnoremap <S-F5> :LLmode code<CR>
    nnoremap <F8> :LL continue<CR>
    nnoremap <S-F8> :LL process interrupt<CR>
    nnoremap <F9> :LL print <C-R>=expand('<cword>')<CR>
    vnoremap <F9> :<C-U>LL print <C-R>=lldb#util#get_selection()<CR><CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <silent> [Window]N :<C-u>call deol#new({'command': 'bash'})<CR>
  nnoremap <silent> [Space]s :<C-u>Deol bash<CR>
  nnoremap <silent> [Window]D  :<C-u>call deol#kill_editor()<CR>
'''
hook_source = '''
  let g:deol#prompt_pattern = '\w*%'
  autocmd FileType deol call s:on_deol()
  function! s:on_deol() abort
    nnoremap <buffer><silent> [Space]gs :<C-u>call deol#send('git status')<CR>
    nnoremap <buffer><silent> [Space]gc :<C-u>call deol#send('git commit')<CR>
    nnoremap <buffer><silent> [Space]gA :<C-u>call deol#send('git commit --amend')<CR>
  endfunction
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

# [[plugins]]
# repo = "huawenyu/neogdb.vim"
# on_ft = ['c', 'cpp']

# [[plugins]]
# repo = 'equalsraf/neovim-gui-shim'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 1
" let g:vim_markdown_folding_level = 6
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
hook_add = '''
let g:table_mode_corner="|"
'''
