[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
autocmd ColorScheme * highlight Comment ctermfg=40 guifg=#008800
autocmd ColorScheme * highlight Visual  ctermbg=236 guibg=grey22
autocmd ColorScheme * hi CursorLine  cterm=NONE ctermbg=236 ctermfg=NONE guibg=grey17 guifg=NONE
autocmd ColorScheme * hi Search cterm=NONE ctermfg=NONE ctermbg=243 guibg=midnightblue guifg=NONE
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = "https://github.com/tyru/caw.vim.git"
hook_add = '''
let g:caw_no_default_keymappings = 1
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
nmap <C-/> <Plug>(caw:hatpos:toggle)
vmap <C-/> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
# repo = 'Townk/vim-autoclose'
repo = 'ivang/vim-autoclose'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
" カーソルキーでbuffer移動
nnoremap <Left> :bp<CR>
nnoremap <Right> :bn<CR>
nnoremap <C-h> :bp<CR>
nnoremap <C-l> :bn<CR>
" Smarter tab line有効化
let g:airline#extensions#tabline#enabled = 1
" powerline font
let g:airline_powerline_fonts = 1
" vim-airline-themes
let g:airline_theme='behelit'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
hook_add = '''
map <Space>r <Plug>(operator-replace)
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-fold'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if  = '''
!has('nvim')
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if  = '''
!has('nvim')
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'zebult/auto-gtags.vim'
hook_add = '''
let g:auto_update_gtags = 1
'''

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
    " Keymap
    " Show definetion of function cousor word on quickfix
    nmap <silent> K :<C-u>exe("Gtags ".expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nmap <silent> R :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
'''

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "chrismccord/bclose.vim"
hook_add = '''
nnoremap <silent> sq :<C-u>Bclose<CR>
'''

[[plugins]]
repo = "kana/vim-tabpagecd"

# [[plugins]]
# repo = "vim-ctrlspace/vim-ctrlspace"

[[plugins]]
repo = "airblade/vim-rooter"
hook_add = '''
let g:rooter_use_lcd = 1
'''

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'equalsraf/neovim-gui-shim'

# [[plugins]]
# repo = 'vim-pandoc/vim-pandoc'
#
# [[plugins]]
# repo = 'vim-pandoc/vim-pandoc-syntax'
